version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_marketing_analysis_api
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev
    expose:
      - 4000
    ports:
      - "4000:4000"
